const List<CurrencyModel> defaultCurrencies = [
  CurrencyModel(name: 'Afghan Afghani', code: 'AFN', symbol: 'Af'),
  CurrencyModel(name: 'Albanian Lek', code: 'ALL', symbol: 'L'),
  CurrencyModel(name: 'Algerian Dinar', code: 'DZD', symbol: 'DA'),
  CurrencyModel(name: 'Angolan Kwanza', code: 'AOA', symbol: 'Kz'),
  CurrencyModel(name: 'Argentine Peso', code: 'ARS', symbol: '\$'),
  CurrencyModel(name: 'Armenian Dram', code: 'AMD', symbol: '֏'),
  CurrencyModel(name: 'Australian Dollar', code: 'AUD', symbol: '\$'),
  CurrencyModel(name: 'Azerbaijani Manat', code: 'AZN', symbol: '₼'),
  CurrencyModel(name: 'Bahamian Dollar', code: 'BSD', symbol: '\$'),
  CurrencyModel(name: 'Bahraini Dinar', code: 'BHD', symbol: 'BD'),
  CurrencyModel(name: 'Bangladeshi Taka', code: 'BDT', symbol: '৳'),
  CurrencyModel(name: 'Belarusian Ruble', code: 'BYN', symbol: 'Br'),
  CurrencyModel(name: 'Bermudian Dollar', code: 'BMD', symbol: '\$'),
  CurrencyModel(name: 'Bolivian Boliviano', code: 'BOB', symbol: 'Bs.'),
  CurrencyModel(name: 'Bosnia-Herzegovina Mark', code: 'BAM', symbol: 'KM'),
  CurrencyModel(name: 'Botswanan Pula', code: 'BWP', symbol: 'P'),
  CurrencyModel(name: 'Brazilian Real', code: 'BRL', symbol: 'R\$'),
  CurrencyModel(name: 'British Pound', code: 'GBP', symbol: '£'),
  CurrencyModel(name: 'Brunei Dollar', code: 'BND', symbol: '\$'),
  CurrencyModel(name: 'Bulgarian Lev', code: 'BGN', symbol: 'лв'),
  CurrencyModel(name: 'Cambodian Riel', code: 'KHR', symbol: '៛'),
  CurrencyModel(name: 'Canadian Dollar', code: 'CAD', symbol: '\$'),
  CurrencyModel(name: 'Chilean Peso', code: 'CLP', symbol: '\$'),
  CurrencyModel(name: 'Chinese Yuan', code: 'CNY', symbol: '¥'),
  CurrencyModel(name: 'Colombian Peso', code: 'COP', symbol: '\$'),
  CurrencyModel(name: 'Costa Rican Colón', code: 'CRC', symbol: '₡'),
  CurrencyModel(name: 'Croatian Kuna', code: 'HRK', symbol: 'kn'),
  CurrencyModel(name: 'Czech Koruna', code: 'CZK', symbol: 'Kč'),
  CurrencyModel(name: 'Danish Krone', code: 'DKK', symbol: 'kr'),
  CurrencyModel(name: 'Dominican Peso', code: 'DOP', symbol: 'RD\$'),
  CurrencyModel(name: 'Egyptian Pound', code: 'EGP', symbol: 'E£'),
  CurrencyModel(name: 'Ethiopian Birr', code: 'ETB', symbol: 'Br'),
  CurrencyModel(name: 'Euro', code: 'EUR', symbol: '€'),
  CurrencyModel(name: 'Georgian Lari', code: 'GEL', symbol: '₾'),
  CurrencyModel(name: 'Ghanaian Cedi', code: 'GHS', symbol: 'GH₵'),
  CurrencyModel(name: 'Guatemalan Quetzal', code: 'GTQ', symbol: 'Q'),
  CurrencyModel(name: 'Hong Kong Dollar', code: 'HKD', symbol: '\$'),
  CurrencyModel(name: 'Hungarian Forint', code: 'HUF', symbol: 'Ft'),
  CurrencyModel(name: 'Icelandic Króna', code: 'ISK', symbol: 'kr'),
  CurrencyModel(name: 'Indian Rupee', code: 'INR', symbol: '₹'),
  CurrencyModel(name: 'Indonesian Rupiah', code: 'IDR', symbol: 'Rp'),
  CurrencyModel(name: 'Iranian Rial', code: 'IRR', symbol: '﷼'),
  CurrencyModel(name: 'Iraqi Dinar', code: 'IQD', symbol: 'ID'),
  CurrencyModel(name: 'Israeli Shekel', code: 'ILS', symbol: '₪'),
  CurrencyModel(name: 'Jamaican Dollar', code: 'JMD', symbol: 'J\$'),
  CurrencyModel(name: 'Japanese Yen', code: 'JPY', symbol: '¥'),
  CurrencyModel(name: 'Jordanian Dinar', code: 'JOD', symbol: 'JD'),
  CurrencyModel(name: 'Kazakhstani Tenge', code: 'KZT', symbol: '₸'),
  CurrencyModel(name: 'Kenyan Shilling', code: 'KES', symbol: 'KSh'),
  CurrencyModel(name: 'Kuwaiti Dinar', code: 'KWD', symbol: 'KD'),
  CurrencyModel(name: 'Lebanese Pound', code: 'LBP', symbol: 'L£'),
  CurrencyModel(name: 'Libyan Dinar', code: 'LYD', symbol: 'LD'),
  CurrencyModel(name: 'Macanese Pataca', code: 'MOP', symbol: 'MOP\$'),
  CurrencyModel(name: 'Malaysian Ringgit', code: 'MYR', symbol: 'RM'),
  CurrencyModel(name: 'Mauritian Rupee', code: 'MUR', symbol: '₨'),
  CurrencyModel(name: 'Mexican Peso', code: 'MXN', symbol: '\$'),
  CurrencyModel(name: 'Mongolian Tugrik', code: 'MNT', symbol: '₮'),
  CurrencyModel(name: 'Moroccan Dirham', code: 'MAD', symbol: 'DH'),
  CurrencyModel(name: 'Myanmar Kyat', code: 'MMK', symbol: 'K'),
  CurrencyModel(name: 'Namibian Dollar', code: 'NAD', symbol: 'N\$'),
  CurrencyModel(name: 'Nepalese Rupee', code: 'NPR', symbol: '₨'),
  CurrencyModel(name: 'New Zealand Dollar', code: 'NZD', symbol: '\$'),
  CurrencyModel(name: 'Nigerian Naira', code: 'NGN', symbol: '₦'),
  CurrencyModel(name: 'Norwegian Krone', code: 'NOK', symbol: 'kr'),
  CurrencyModel(name: 'Omani Rial', code: 'OMR', symbol: 'RO'),
  CurrencyModel(name: 'Pakistani Rupee', code: 'PKR', symbol: '₨'),
  CurrencyModel(name: 'Panamanian Balboa', code: 'PAB', symbol: 'B/.'),
  CurrencyModel(name: 'Paraguayan Guarani', code: 'PYG', symbol: '₲'),
  CurrencyModel(name: 'Peruvian Sol', code: 'PEN', symbol: 'S/.'),
  CurrencyModel(name: 'Philippine Peso', code: 'PHP', symbol: '₱'),
  CurrencyModel(name: 'Polish Zloty', code: 'PLN', symbol: 'zł'),
  CurrencyModel(name: 'Qatari Riyal', code: 'QAR', symbol: 'QR'),
  CurrencyModel(name: 'Romanian Leu', code: 'RON', symbol: 'lei'),
  CurrencyModel(name: 'Russian Ruble', code: 'RUB', symbol: '₽'),
  CurrencyModel(name: 'Saudi Riyal', code: 'SAR', symbol: 'SR'),
  CurrencyModel(name: 'Serbian Dinar', code: 'RSD', symbol: 'din'),
  CurrencyModel(name: 'Singapore Dollar', code: 'SGD', symbol: '\$'),
  CurrencyModel(name: 'South African Rand', code: 'ZAR', symbol: 'R'),
  CurrencyModel(name: 'South Korean Won', code: 'KRW', symbol: '₩'),
  CurrencyModel(name: 'Sri Lankan Rupee', code: 'LKR', symbol: 'Rs'),
  CurrencyModel(name: 'Swedish Krona', code: 'SEK', symbol: 'kr'),
  CurrencyModel(name: 'Swiss Franc', code: 'CHF', symbol: 'CHF'),
  CurrencyModel(name: 'Taiwan New Dollar', code: 'TWD', symbol: 'NT\$'),
  CurrencyModel(name: 'Tanzanian Shilling', code: 'TZS', symbol: 'TSh'),
  CurrencyModel(name: 'Thai Baht', code: 'THB', symbol: '฿'),
  CurrencyModel(name: 'Tunisian Dinar', code: 'TND', symbol: 'DT'),
  CurrencyModel(name: 'Turkish Lira', code: 'TRY', symbol: '₺'),
  CurrencyModel(name: 'UAE Dirham', code: 'AED', symbol: 'DH'),
  CurrencyModel(name: 'Ugandan Shilling', code: 'UGX', symbol: 'USh'),
  CurrencyModel(name: 'Ukrainian Hryvnia', code: 'UAH', symbol: '₴'),
  CurrencyModel(name: 'Uruguayan Peso', code: 'UYU', symbol: '\$U'),
  CurrencyModel(name: 'US Dollar', code: 'USD', symbol: '\$'),
  CurrencyModel(name: 'Uzbekistani Som', code: 'UZS', symbol: 'soʻm'),
  CurrencyModel(name: 'Vietnamese Dong', code: 'VND', symbol: '₫'),
  CurrencyModel(name: 'West African CFA Franc', code: 'XOF', symbol: 'CFA'),
  CurrencyModel(name: 'Zambian Kwacha', code: 'ZMW', symbol: 'ZK'),
];

class CurrencyModel {
  final String name;
  final String code;
  final String symbol;

  const CurrencyModel({
    required this.name,
    required this.code,
    required this.symbol,
  });
}
